### ISSUE TITLE
Jump button is unclear to new players

### ISSUE THREAD

**Issue by N1ckn1ght** [captaincod/FlappyBomb#1]
I found it by bruteforce (it's SPACE), however it hasn't been mentioned at any game screen.

You could mention it anywhere;

Alternative idea is to make jump button on ENTER since player needs to press it in order to start a game,

or make start button on SPACE as well.

**Comment by captaincod** [comment]
Now that's fixed, thank you  
![image](https://user-images.githubusercontent.com/46486971/208497974-c2de9192-6b3b-45d8-8abf-4cbbfe1de5f9.png)
